sudo: false
language: node_js
node_js:
  - 11.10.0
branches:
  only:
    - master
    - develop
cache:
  directories:
    - node_modules
    - package/node_modules
    - package/.rpt2_cache
install:
  - npm install
  - npm run bootstrap
script:
  - npm test
  - npm run build
